export const Fooditems = [
    {
        id: 1,
        title: 'Chicken Burger',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'burger',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/sHPbJPQ/peter-dawn-sx-Z-Ca6-Mk-WM-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 2,
        title: 'Chicken Pizza',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'pizza',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/9cNmLQC/mike-Px-J9zk-M2wd-A-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 3,
        title: 'French Fry',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'french fry',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/HqdRwtQ/ivan-torres-MQUqbmsz-GGM-unsplash.jpg',
        shopName: 'food court'
    },
    {
        id: 4,
        title: 'Dark Cup Cake',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'cake',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/HqdRwtQ/ivan-torres-MQUqbmsz-GGM-unsplash.jpg',
        shopName: 'tasty treat'
    },
    {
        id: 5,
        title: 'Shripm Ramen',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'shripm ramen',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/vjDkMK4/haseeb-jamil-J9l-D6-FS6-cs-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 6,
        title: 'Chicken Burger',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'burger',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/kMrftW2/brett-jordan-m8p-KY-8bdyo-unsplash.jpg',
        shopName: 'Food Court'
    },
    {
        id: 7,
        title: 'Sweet Cup',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'cake',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'tasty treat'
    },
    {
        id: 8,
        title: 'Beep Pizza',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'pizza',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/D5rvzg8/amirali-mirhashemian-puc-P6j-ZSy-V4-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 9,
        title: 'Yogurt',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'icecream',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'food court'
    },
    {
        id: 10,
        title: 'Chicken Burger',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'burger',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/sHPbJPQ/peter-dawn-sx-Z-Ca6-Mk-WM-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 11,
        title: 'Chicken Pizza',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'pizza',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/9cNmLQC/mike-Px-J9zk-M2wd-A-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 12,
        title: 'French Fry',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'french fry',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/HqdRwtQ/ivan-torres-MQUqbmsz-GGM-unsplash.jpg',
        shopName: 'food court'
    },
    {
        id: 13,
        title: 'Dark Cup Cake Pro',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'cake',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/HqdRwtQ/ivan-torres-MQUqbmsz-GGM-unsplash.jpg',
        shopName: 'tasty treat'
    },
    {
        id: 14,
        title: 'Shripm Ramen',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'shripm ramen',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/vjDkMK4/haseeb-jamil-J9l-D6-FS6-cs-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 15,
        title: 'Chicken Burger',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'burger',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/kMrftW2/brett-jordan-m8p-KY-8bdyo-unsplash.jpg',
        shopName: 'safus'
    },
    {
        id: 16,
        title: 'Sweet Cup Pro',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'cake',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'tasty treat'
    },
    {
        id: 17,
        title: 'Beep Pizza',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'pizza',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/D5rvzg8/amirali-mirhashemian-puc-P6j-ZSy-V4-unsplash.jpg',
        shopName: 'safus'
    },
    {
        id: 18,
        title: 'Yogurt Pro',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'icecream',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 9,
        title: 'Yogurt',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'icecream',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'green garden'
    },
    {
        id: 9,
        title: 'Yogurt pro',
        description: 'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        price: 300,
        quantity: '',
        stock: 100,
        category: 'icecream',
        totalsale: 34,
        createdAt: new Date(),
        updatedAt: new Date(),
        image: 'https://i.ibb.co/Cbby8Qy/ashim-d-silva-RNt-DCo-V7o4c-unsplash.jpg',
        shopName: 'food court'
    },
]



export const ServicesItem = [
    {
        id: 1,
        title: 'Online Order',
        image: '/assets/OnlineOrder.png'
    },
    {
        id: 2,
        title: 'Smart Delivery',
        image: '/assets/Kiti 2.png'
    },
    {
        id: 3,
        title: 'Smart Pickup',
        image: '/assets/Kiti2.png'
    }

]


export const robotsList = [
    {
        id:1,
        robotName:'kiti 1',
        selected:false,
        live:true,
    },
    {
        id:2,
        robotName:'kiti 2',
        selected:false,
        live:true,
    },
    {
        id:3,
        robotName:'kiti 3',
        selected:false,
        live:true,
    },
    {
        id:4,
        robotName:'kiti 4',
        selected:false,
        live:false,
    },
    {
        id:5,
        robotName:'kiti 5',
        selected:false,
        live:false,
    },
    {
        id:6,
        robotName:'kiti 6',
        selected:false,
        live:false,
    },
    {
        id:7,
        robotName:'kiti 7',
        selected:false,
        live:false,
    },
    {
        id:8,
        robotName:'kiti 8',
        selected:false,
        live:true,
    },
    {
        id:9,
        robotName:'kiti 9',
        selected:false,
        live:true,
    },
]
